# Generated by Django 3.0.2 on 2020-02-06 17:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0004_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='stock',
            name='stock_type',
            field=models.CharField(choices=[('fund', 'FUND'), ('equity', 'EQUITY')], default='equity', max_length=6),
        ),
    ]
