# Generated by Django 3.0.2 on 2020-02-06 20:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0005_stock_stock_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stock',
            name='stock_type',
            field=models.CharField(choices=[('fund', 'FUND'), ('equity', 'EQUITY'), ('etfs', 'ETFS')], default='equity', max_length=6),
        ),
    ]
