# Generated by Django 3.0.2 on 2020-02-07 12:19

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0009_auto_20200207_0822'),
    ]

    operations = [
        migrations.AddField(
            model_name='stock',
            name='current_price',
            field=models.DecimalField(decimal_places=2, default=1.0, max_digits=7),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='stock',
            name='price_updated',
            field=models.DateTimeField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
