# Generated by Django 3.0.3 on 2020-02-12 10:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0013_auto_20200207_1506'),
    ]

    operations = [
        migrations.AddField(
            model_name='stock',
            name='nickname',
            field=models.CharField(default='nickname', max_length=40),
            preserve_default=False,
        ),
    ]
