# Generated by Django 3.0.2 on 2020-02-12 20:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0015_auto_20200212_1105'),
    ]

    operations = [
        migrations.AddField(
            model_name='holding',
            name='value_updated',
            field=models.DateTimeField(null=True),
        ),
    ]
