# Generated by Django 3.0.3 on 2020-04-16 18:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0018_account_person'),
    ]

    operations = [
        migrations.AddField(
            model_name='stock',
            name='yahoo_code',
            field=models.CharField(default='codehere', max_length=20),
            preserve_default=False,
        ),
        migrations.CreateModel(
            name='HistoricPrice',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(blank=True)),
                ('open', models.DecimalField(decimal_places=2, max_digits=7)),
                ('high', models.DecimalField(decimal_places=2, max_digits=7)),
                ('low', models.DecimalField(decimal_places=2, max_digits=7)),
                ('close', models.DecimalField(decimal_places=2, max_digits=7)),
                ('adjclose', models.DecimalField(decimal_places=2, max_digits=7)),
                ('stock', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='portfolio.Stock')),
            ],
            options={
                'ordering': ['-date', 'stock'],
            },
        ),
    ]
