# Generated by Django 3.0.3 on 2020-04-17 09:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0019_auto_20200416_1842'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historicprice',
            name='date',
            field=models.DateField(blank=True),
        ),
    ]
