# Generated by Django 3.0.3 on 2020-08-21 15:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0022_auto_20200418_1633'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='account',
            options={'ordering': ['account_type']},
        ),
        migrations.AlterModelOptions(
            name='historicprice',
            options={'ordering': ['-date']},
        ),
        migrations.AddField(
            model_name='stock',
            name='perf_1m',
            field=models.DecimalField(decimal_places=2, max_digits=7, null=True),
        ),
        migrations.AddField(
            model_name='stock',
            name='perf_1y',
            field=models.DecimalField(decimal_places=2, max_digits=7, null=True),
        ),
        migrations.AddField(
            model_name='stock',
            name='perf_3m',
            field=models.DecimalField(decimal_places=2, max_digits=7, null=True),
        ),
        migrations.AddField(
            model_name='stock',
            name='perf_3y',
            field=models.DecimalField(decimal_places=2, max_digits=7, null=True),
        ),
        migrations.AddField(
            model_name='stock',
            name='perf_5y',
            field=models.DecimalField(decimal_places=2, max_digits=7, null=True),
        ),
        migrations.AddField(
            model_name='stock',
            name='perf_6m',
            field=models.DecimalField(decimal_places=2, max_digits=7, null=True),
        ),
        migrations.AlterField(
            model_name='account',
            name='account_type',
            field=models.CharField(choices=[('ISA', 'ISA'), ('pension', 'PENSION'), ('standard', 'STANDARD'), ('VCT', 'VCT')], default='buy', max_length=8),
        ),
    ]
