# Generated by Django 3.1.5 on 2021-04-10 17:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0024_stock_stock_region'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stock',
            name='stock_region',
            field=models.CharField(choices=[('world', 'WORLD'), ('us', 'US'), ('uk', 'UK'), ('europe', 'EUROPE')], default='world', max_length=6),
        ),
    ]
