# Generated by Django 3.2.3 on 2021-06-21 18:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0027_alter_stock_stock_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stock',
            name='current_price',
            field=models.DecimalField(decimal_places=4, max_digits=7),
        ),
    ]
