# Generated by Django 3.2.3 on 2021-09-02 10:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0028_alter_stock_current_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='account_type',
            field=models.CharField(choices=[('ISA', 'ISA'), ('pension', 'PENSION'), ('standard', 'STANDARD'), ('VCT', 'VCT'), ('cash', 'CASH')], default='buy', max_length=8),
        ),
    ]
