# Generated by Django 5.0.1 on 2024-11-04 17:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0029_alter_account_account_type'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='account',
            options={'ordering': ['name']},
        ),
    ]
